# Generated by Django 2.1.3 on 2018-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form_available',
        ),
        migrations.RemoveField(
            model_name='field',
            name='list_available',
        ),
        migrations.RemoveField(
            model_name='groupfield',
            name='form_available',
        ),
        migrations.RemoveField(
            model_name='groupfield',
            name='list_available',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='form_available',
        ),
        migrations.RemoveField(
            model_name='userfield',
            name='list_available',
        ),
        migrations.AddField(
            model_name='field',
            name='exportable',
            field=models.BooleanField(default=True, verbose_name='可导出'),
        ),
        migrations.AddField(
            model_name='field',
            name='formable',
            field=models.BooleanField(default=True, verbose_name='在表单中显示'),
        ),
        migrations.AddField(
            model_name='field',
            name='listable',
            field=models.BooleanField(default=True, verbose_name='在列表中显示'),
        ),
        migrations.AddField(
            model_name='field',
            name='sortable',
            field=models.BooleanField(default=True, verbose_name='可排序'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='exportable',
            field=models.BooleanField(default=True, verbose_name='可导出'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='formable',
            field=models.BooleanField(default=True, verbose_name='在表单中显示'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='listable',
            field=models.BooleanField(default=True, verbose_name='在列表中显示'),
        ),
        migrations.AddField(
            model_name='groupfield',
            name='sortable',
            field=models.BooleanField(default=True, verbose_name='可排序'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='exportable',
            field=models.BooleanField(default=True, verbose_name='可导出'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='formable',
            field=models.BooleanField(default=True, verbose_name='在表单中显示'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='listable',
            field=models.BooleanField(default=True, verbose_name='在列表中显示'),
        ),
        migrations.AddField(
            model_name='userfield',
            name='sortable',
            field=models.BooleanField(default=True, verbose_name='可排序'),
        ),
    ]
