# Generated by Django 2.1.3 on 2018-12-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('base', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='groupfield',
            unique_together={('group', 'base', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='userfield',
            unique_together={('user', 'base', 'attribute')},
        ),
    ]
