# Generated by Django 2.1.3 on 2018-12-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcontenttype',
            options={'ordering': ['group', 'sequence'], 'verbose_name': '模型(用户组)', 'verbose_name_plural': '模型(用户组)'},
        ),
        migrations.AlterModelOptions(
            name='usercontenttype',
            options={'ordering': ['user', 'sequence'], 'verbose_name': '模型(用户)', 'verbose_name_plural': '模型(用户)'},
        ),
        migrations.RemoveField(
            model_name='groupcontenttype',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='groupcontenttype',
            name='contenttype',
        ),
        migrations.RemoveField(
            model_name='usercontenttype',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='usercontenttype',
            name='contenttype',
        ),
        migrations.AddField(
            model_name='groupcontenttype',
            name='app',
            field=models.CharField(default=1, max_length=100, verbose_name='应用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcontenttype',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupcontenttype',
            name='sequence',
            field=models.IntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='groupcontenttype',
            name='verbose_name',
            field=models.CharField(default=1, max_length=100, verbose_name='描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontenttype',
            name='app',
            field=models.CharField(default=1, max_length=100, verbose_name='应用'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontenttype',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontenttype',
            name='sequence',
            field=models.IntegerField(default=100, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='usercontenttype',
            name='verbose_name',
            field=models.CharField(default=1, max_length=100, verbose_name='描述'),
            preserve_default=False,
        ),
    ]
