# Generated by Django 2.1.3 on 2018-12-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0002_grouppermission_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acmin.Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermission',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acmin.Model'),
            preserve_default=False,
        ),
    ]
