# Generated by Django 2.1.3 on 2018-12-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0002_auto_20181203_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupcontenttype',
            unique_together={('group', 'app', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='usercontenttype',
            unique_together={('user', 'app', 'name')},
        ),
    ]
