# Generated by Django 2.1.3 on 2018-12-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0002_auto_20181203_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['base', 'group_sequence', 'sequence'], 'verbose_name': '字段', 'verbose_name_plural': '字段'},
        ),
        migrations.AlterModelOptions(
            name='groupfield',
            options={'ordering': ['base', 'group_sequence', 'sequence'], 'verbose_name': '字段(用户组)', 'verbose_name_plural': '字段(用户组)'},
        ),
        migrations.AlterModelOptions(
            name='userfield',
            options={'ordering': ['base', 'group_sequence', 'sequence'], 'verbose_name': '字段(用户)', 'verbose_name_plural': '字段(用户)'},
        ),
    ]
