# Generated by Django 2.1.3 on 2018-12-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0003_auto_20181201_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpermission',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
