# Generated by Django 2.1.3 on 2018-12-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0004_auto_20181201_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperPermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '所用模型',
                'verbose_name_plural': '所用模型',
                'ordering': ['-id'],
            },
        ),
    ]
