# Generated by Django 2.1.3 on 2018-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0006_auto_20181201_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppermission',
            name='cloneable',
            field=models.BooleanField(default=False, verbose_name='可复制'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='creatable',
            field=models.BooleanField(default=False, verbose_name='可创建'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='开通'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='exportable',
            field=models.BooleanField(default=False, verbose_name='可导出'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='listable',
            field=models.BooleanField(default=False, verbose_name='可列表'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='removable',
            field=models.BooleanField(default=False, verbose_name='可删除'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='savable',
            field=models.BooleanField(default=False, verbose_name='可保存'),
        ),
        migrations.AlterField(
            model_name='grouppermission',
            name='viewable',
            field=models.BooleanField(default=False, verbose_name='可查看'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='cloneable',
            field=models.BooleanField(default=False, verbose_name='可复制'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='creatable',
            field=models.BooleanField(default=False, verbose_name='可创建'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='enabled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='开通'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='exportable',
            field=models.BooleanField(default=False, verbose_name='可导出'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='listable',
            field=models.BooleanField(default=False, verbose_name='可列表'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='removable',
            field=models.BooleanField(default=False, verbose_name='可删除'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='savable',
            field=models.BooleanField(default=False, verbose_name='可保存'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='viewable',
            field=models.BooleanField(default=False, verbose_name='可查看'),
        ),
    ]
