# Generated by Django 2.1.3 on 2018-12-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmin', '0007_auto_20181201_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppermission',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='enabled',
        ),
    ]
