# Generated by Django 2.1.3 on 2018-12-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='代码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=150, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=150, verbose_name='名称'),
        ),
    ]
