# Generated by Django 2.1.3 on 2018-11-30 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickFarming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, verbose_name='订单号')),
                ('exprense', models.FloatField(verbose_name='刷单费用')),
                ('express_fee', models.FloatField(default=0, verbose_name='快递费')),
                ('tracking_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递单号')),
                ('reimbursed', models.BooleanField(default=False, verbose_name='已报销?')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('reimburse_time', models.DateTimeField(null=True, verbose_name='报销时间')),
            ],
            options={
                'verbose_name': '刷单',
                'verbose_name_plural': '刷单',
                'ordering': ['reimbursed', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='事项')),
                ('exprense', models.FloatField(verbose_name='费用')),
                ('reimbursed', models.BooleanField(default=False, verbose_name='已报销')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '其他支出',
                'verbose_name_plural': '其他支出',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '平台',
                'verbose_name_plural': '平台',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='clickfarming',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Platform', verbose_name='电商平台'),
        ),
        migrations.AddField(
            model_name='clickfarming',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者'),
        ),
    ]
