# Generated by Django 2.1.3 on 2018-12-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20181130_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickfarming',
            old_name='exprense',
            new_name='expense',
        ),
    ]
