# Generated by Django 2.1.4 on 2018-12-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20181206_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'man'), (0, 'woman')], default=0),
        ),
    ]
