# Generated by Django 2.1.3 on 2019-01-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'man'), (0, 'woman')], default=0, verbose_name='性别'),
        ),
    ]
