# Generated by Django 2.2.2 on 2019-07-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20190107_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='is_capital',
            field=models.SmallIntegerField(choices=[(3, '是'), (5, '否')], default=5, verbose_name='是否首都'),
        ),
    ]
